/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Base tokens
        background: "#F7F5F1",
        foreground: "#111111",
        surface: "#F7F5F1",
        "on-surface": "#111111",
        "surface-dim": "#ddd9d8",
        "surface-bright": "#fdf8f8",
        "surface-variant": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3f2",
        "surface-container": "#f1edec",
        "surface-container-high": "#ebe7e6",
        "surface-container-highest": "#e5e2e1",
        "on-surface-variant": "#444748",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        "surface-tint": "#5f5e5e",
        
        // Brand palette aliases
        ivory: "#F7F5F1",
        ink: "#111111",
        stone: "#6B6862",
        hairline: "#E4E1DA",

        // Primary / Secondary / Tertiary tokens
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "inverse-primary": "#c8c6c5",

        secondary: "#615e58",
        "on-secondary": "#ffffff",
        "secondary-container": "#e7e2da",
        "on-secondary-container": "#67645e",
        "secondary-fixed": "#e7e2da",
        "secondary-fixed-dim": "#cbc6bf",
        "on-secondary-fixed": "#1d1b17",
        "on-secondary-fixed-variant": "#494641",

        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1c1c18",
        "on-tertiary-container": "#85847e",
        "tertiary-fixed": "#e5e2db",
        "tertiary-fixed-dim": "#c9c6c0",
        "on-tertiary-fixed": "#1c1c18",
        "on-tertiary-fixed-variant": "#484742",

        outline: "#747878",
        "outline-variant": "#E4E1DA",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        serif: ["Fraunces", "var(--font-fraunces)", "serif"],
        sans: ["Plus Jakarta Sans", "Jost", "var(--font-jost)", "sans-serif"],
        "display-lg": ["Fraunces", "serif"],
        "headline-lg": ["Fraunces", "serif"],
        "headline-md": ["Fraunces", "serif"],
        "headline-sm": ["Fraunces", "serif"],
        "headline-lg-mobile": ["Fraunces", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "nav-link": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["84px", { lineHeight: "92px", letterSpacing: "-0.02em", fontWeight: "300" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "nav-link": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
